<?php
use yii\helpers\Url;

return [
    'title' => 'Privacy Policy',
    'htm_text' => '
<h1>Privacy Policy</h1>


<p>Effective date: November 22, 2018</p>


<p>PB Private Cloud Solutions Ltd. ("us", "we", or "our") operates the Pvtbox.net ("Website", or "Service") and the {APP_NAME} desktop and  mobile application ("Application", or "Service")</p>

<p>This Privacy Policy informs you of our policies regarding collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. Unless otherwise defined herein, the terms used in this Privacy Policy have the same meanings as in our <a href="' . Url::to(['/terms'], CREATE_ABSOLUTE_URL) . '">Terms and Conditions</a></p>

<h2>Definitions</h2>
<ul>
    <li>
        <p><strong>"Service"</strong> means our Website and Application operated by Pb Private Cloud Solutions Ltd.</p>
    </li>
    <li>
        <p><strong>"Personal Data"</strong> means data about the living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    </li>
    <li>
        <p><strong>"Usage Data"</strong> means data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
    </li>
    <li>
        <p><strong>"Cookies"</strong> means small files stored on your device (computer or mobile device).</p>
    </li>
    <li>
        <p><strong>"Data Controller"</strong> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
        <p>For the purpose of this Privacy Policy, we serve as Data Controller of your Personal Data.</p>
    </li>
    <li>
        <p><strong>"Data Processor"</strong> or <strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Data Controller.</p>
        <p>We may use the services of various Service Providers in order to process your data more effectively.</p>
    </li>
    <li>
        <p><strong>"Data Subject"</strong> or <strong>"User"</strong> is any living individual who is using our Service and is the subject of Personal Data.</p>
    </li>
</ul>


<h2>Information Collection and Use</h2>
<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

<h4>1. Personal Data</h4>
<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to email address, cookies and usage data.</p>

<p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by contacting us.</p>

<h4>2. Usage Data</h4>

<p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</p>
<p>This Usage Data may include information such as your computer\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>


<h4>3. Tracking & Cookies Data</h4>
<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
<p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
<p>To learn more about our use of cookies, please read our Cookies Policy.</p>


<h1>Cookies Policy</h1>

<p>Cookies are small pieces of text sent to your web browser by a website you visit. A cookie file is stored in your web browser and allows the Service or a third-party to recognize you and make your next visit easier and the Service more useful to you.</p>

<p>Cookies can be "persistent" or "session" cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser.</p>

<h2>How Pb Private Cloud Solutions Ltd. uses cookies</h2>

<p>When you use and access the Service, we may place a number of cookies files in your web browser.</p>

<p>We use cookies for the following purposes:</p>

<ul>
<li>
    <p>To enable certain functions of the Service</p>
</li>
<li>
    <p>To store your preferences</p>
</li>
</ul>

<p>We use both session and persistent cookies on the Service and we use different types of cookies to run the Service:</p>

<ul>
<li>
    <p>Essential cookies. We may use cookies to remember information that changes the way the Service behaves or looks, such as a user\'s language preference on the Service.</p>
</li>
<li>
    <p>Accounts-related cookies. We may use accounts-related cookies to authenticate users and prevent fraudulent use of user accounts. We may use these cookies to remember information that changes the way the Service behaves or looks, such as the "remember me" functionality.</p>
</li>
</ul>


<h2>What are your choices regarding cookies</h2>

<p>If you\'d like to delete cookies or instruct your web browser to delete or refuse cookies, please visit the help pages of your web browser.</p>

<p>Please note, however, that if you delete cookies or refuse to accept them, you might not be able to use all of the features we offer, you may not be able to store your preferences, and some of our pages might not display properly.</p>

<ul>
<li>
    <p>For the Chrome web browser, please visit this page from Google: <a href="https://support.google.com/accounts/answer/32050">https://support.google.com/accounts/answer/32050</a></p>
</li>
<li>
    <p>For the Internet Explorer web browser, please visit this page from Microsoft: <a href="http://support.microsoft.com/kb/278835">http://support.microsoft.com/kb/278835</a></p>
</li>
<li>
    <p>For the Firefox web browser, please visit this page from Mozilla: <a href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a></p>
</li>
<li>
    <p>For the Safari web browser, please visit this page from Apple: <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac">https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a></p>
</li>
<li>
    <p>For any other web browser, please visit your web browser\'s official web pages.</p>
</li>
</ul>

<h2>Where can you find more information about cookies</h2>

<p>You can learn more about cookies and the following third-party websites:</p>

<ul>
<li>
    <p>All About Cookies: <a href="http://www.allaboutcookies.org/">http://www.allaboutcookies.org/</a></p>
</li>
<li>
    <p>Network Advertising Initiative: <a href="http://www.networkadvertising.org/">http://www.networkadvertising.org/</a></p>
</li>
</ul>






<h2>Use of Data</h2>
<p>Pb Private Cloud Solutions Ltd. uses the collected data for various purposes, such as to:</p>
<ul>
    <li>Provide and maintain our Service;</li>
    <li>Notify you about changes to our Service;</li>
    <li>Allow you to participate in interactive features of our Service when you choose to do so;</li>
    <li>Provide customer support;</li>
    <li>Gather analysis or valuable information so that we can improve our Service</li>
    <li>Monitor the usage of our Service;</li>
    <li>Detect, prevent and address technical issues;</li>
    <li>Provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
</ul>
<p><b>We don\'t sell your personal data to others.</b></p>


<h2>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h2>
<p>If you are from the European Economic Area (EEA), Pb Private Cloud Solutions Ltd. legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
<p>Pb Private Cloud Solutions Ltd. may process your Personal Data because:</p>
<ul>
    <li>We need to perform a contract with you;</li>
    <li>You have given us permission to do so;</li>
    <li>The processing is in our legitimate interests and it is not overridden by your rights;</li>
    <li>For payment processing purposes;</li>    <li>To comply with the law</li>
</ul>


<h2>Data Retention</h2>
<p>Pb Private Cloud Solutions Ltd. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
<p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except for when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

<h2>Data Transfer</h2>
<p>Your data, including Personal Data, may be transferred to, and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
<p>If you are located outside United Kingdom and choose to provide information to us, please note that we transfer all data, including Personal Data to United Kingdom and process it there.</p>
<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
<p>Pb Private Cloud Solutions Ltd. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

<h2>Data Disclosure</h2>


<p>PB Private Cloud Solutions Ltd. may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
    <li>Comply with a legal obligation;</li>
    <li>Protect and defend the rights or property of the Company;</li>
    <li>Prevent or investigate possible wrongdoing in connection with the Service;</li>
    <li>Protect the personal safety of users of the Service or the public;</li>
    <li>Protect against legal liability;</li>
</ul>

<h2>Data Security</h2>
<p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

<h2>Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</h2>
<p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
<p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

<h2>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
<p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Pb Private Cloud Solutions Ltd. aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
<p>If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
<p>In certain circumstances, you have the following data protection rights:</p>
<ul>
    <li>
        <p><strong>The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
    </li>
    <li>
        <p><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
    </li>
    <li>
        <p><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</p>
    </li>
    <li>
        <p><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</p>
    </li>
    <li>
        <p><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
    </li>
    <li>
        <p><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Pb Private Cloud Solutions Ltd. relied on your consent to process your personal information.</p>
    </li>
</ul>
<p>Please note that we may ask you to verify your identity before responding to such requests.</p>

<p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

<h2>Service Providers</h2>
<p>We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>





<h3>Payments</h3>
<p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
<p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American
    Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
<p>The payment processors we work with are:</p>
<ul>
    <li>
        <p><strong>Apple Store In-App Payments</strong></p>
        <p>Their Privacy Policy can be viewed at <a href="https://www.apple.com/legal/privacy/en-ww/">https://www.apple.com/legal/privacy/en-ww/</a></p>
    </li>
    <li>
        <p><strong>Google Play In-App Payments</strong></p>
        <p>Their Privacy Policy can be viewed at <a href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a></p>
    </li>
    <li>
        <p><strong>PayPal / Braintree</strong></p>
        <p>Their Privacy Policy can be viewed at <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">https://www.paypal.com/webapps/mpp/ua/privacy-full</a></p>
    </li>
</ul>


<h2>Links To Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third-party website. We strongly advise you to review the Privacy Policy of every website you visit.</p>
<p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third-party websites or services.</p>


<h2>Children\'s Privacy</h2>
<p>Our Service does not address anyone under the age of 18 ("Children").</p>
<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


<h2>Changes to This Privacy Policy</h2>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, please contact us:</p>
<ul>
    <li>By email: <a href="mailto:{supportEmail_TECHNICAL}">{supportEmail_TECHNICAL}</a></li>
    <li>By visiting this page on our website: <a href="' . Url::to(['/support'], CREATE_ABSOLUTE_URL) . '">' . Url::to(['/support'], true) . '</a></li>

</ul>
    ',
];
